### ISSUE TITLE
TVL not showing for following projects

### ISSUE THREAD

**Issue by januszgrze** [bitcoinlayers/bitcoinlayers#141]
We do not have TVL showing for the following projects on their project page:

- Bsquared Network
- Fractal
- ICP
- Lightning
- Liquid
- Rollux

We're also missing the following projects in the charts section:

- Bsquared
- Fractal
- Rollux

Let's prioritize where the gaps are and getting these projects listed ASAP

**Comment by bolander72** [comment]
1) The front end is wired up and making calls for chart data for the first bullet list. The data is returning an empty array meaning there's no data in DB for those projects.

2) For second bulleted list, those are not appearing in BTC Locked chart on root/layers page because they are NOT bitcoin only. That can be changed if needed

**Comment by bolander72** [comment]
I am seeing Liquid TVL data on project page.

Also for reference - https://github.com/bitcoinlayers/bitcoinlayers/issues/94

**Comment by bolander72** [comment]
- Bsquared
- Fractal
- Rollux

Need to be added to /get_layertvl_historical_bitcoinonly @RedVelvetZip. If there is bitcoinOnly bool check happening, we need to allow for these.

**Comment by bolander72** [comment]
We don't yet have data ingestion setup for Bsquared Network, Fractal, ICP or Rollux

**Comment by RedVelvetZip** [comment]
working on ingesting data for b2, fractal, and rollux
we have ICP

**Comment by RedVelvetZip** [comment]
Bsquared added
missing completely: Fractal, Rollux
need backfills: Stacks, Liquid

**Comment by januszgrze** [comment]
closing this as new data base work has been ongoing and all projects are prioritized
