### ISSUE TITLE
Add Lightning Network research on vulnerabilities, vector attacks and privacy

### ISSUE THREAD

**Issue by stackingsaunter** [bitcoinlayers/bitcoinlayers#33]
- [Mass Exit Attacks on Lightning Network](https://arxiv.org/pdf/2208.01908)

- [Replacement Cycling Attack on the Lightning Network](https://github.com/ariard/mempool-research/blob/2023-10-replacement-paper/replacement-cycling.pdf)

- [A Centrality Analysis of the Lightning Network](https://link.springer.com/chapter/10.1007/978-3-031-18283-9_18)

- [A Quantitative Analysis of Security, Anonymity and Scalability for the Lightning Network](https://ieeexplore.ieee.org/abstract/document/9229723)

- [Flood & Loot: A Systemic Attack on The Lightning Network](https://dl.acm.org/doi/abs/10.1145/3419614.3423248)

- [On the robustness of Lightning Network in Bitcoin](https://www.sciencedirect.com/science/article/abs/pii/S1574119219304730)

- [Discharged Payment Channels: Quantifying the Lightning Network's Resilience to Topology-Based Attacks](https://ieeexplore.ieee.org/abstract/document/8802506)

- [Improvements of the Balance Discovery Attack on Lightning Network Payment Channels](https://link.springer.com/chapter/10.1007/978-3-030-58201-2_21)

Privacy related:

- [Lightning Privacy Research](https://lightningprivacy.com/en/introduction)

- [An Empirical Analysis of Privacy in the Lightning Network
](https://link.springer.com/chapter/10.1007/978-3-662-64322-8_8)

**Comment by januszgrze** [comment]
@veronikakuett - let's discuss if we should add any of these things to the review.

**Comment by veronikakuett** [comment]
> @veronikakuett - let's discuss if we should add any of these things to the review.

My suggestion: 

* Mass Exit attack paper -> undecided. it builds on flood&loot & findings don't seem to be groundbreaking 
* Replacement Cycling -> Yes, but link it in the respective section where it was mentioned in the review, not in Knowledge Bits
* Centrality Analysis -> No. Doesn't directly affect users funds
* Quantitative Analysis.. -> Undecided. Rather not. Non-OS resource. While describing foundational attacks (like wormhole), much of the paper seems to revolve around the state of LN at that point in time (2020). LN topology matured / evolved quite a bit since then. 
* Flood & Loot -> Yes. Non-OS source unfortunately, but seems to be one of the earlier works describing this attack. 
* Robustness.. -> No. Non-OS and available content doesn't come across as groundbreaking. Further, I don't see it much mentioned in other papers. 
* Discharged.. -> Yes. Unfortunately non-OS, but seems valuable resource and referenced in other papers. 
* Improvements.. -> No. 

* Privacy Research. -> Yes. 
* Empirical Analysis. -> No. 

I perceive the following sources as valuable: 
* 2024. Payout Races and Congested Channels: A Formal Analysis of
Security in the Lightning Network. https://arxiv.org/abs/2405.02147 
* 2022. Unjamming Lightning: A Systematic Approach. https://eprint.iacr.org/2022/1454

**Comment by januszgrze** [comment]
closing this as uncompleted for the time being
